import clientPromise from '../../../lib/mongodb'

export default async function handler(req, res){
  const client = await clientPromise
  const db = client.db(process.env.MONGODB_DB || 'granit')
  const col = db.collection('products')
  const sample = [{"name": "Пам'ятник гранітний 'Класик'", "short_description": "Чорний граніт, класичний дизайн", "long_description": "Матеріал: чорний граніт. Розміри: 80x60x10 см. Можливість гравірування.", "price": 8500, "images": ["/sample-images/sample1.jpg"]}, {"name": "Комплекс гранітний 'Еліт'", "short_description": "Комплекс з постаментом та огорожею", "long_description": "Комплекс включає постамент, плити та огорожу. Індивідуальні розміри.", "price": 25000, "images": ["/sample-images/sample2.jpg"]}, {"name": "Плитка з граніту 'Флорент'", "short_description": "Термостійка і довговічна плитка", "long_description": "Гранітна плитка для фасадів і внутрішнього оздоблення.", "price": 450, "images": ["/sample-images/sample3.jpg"]}, {"name": "Раковина гранітна 'Модерн'", "short_description": "Стильна раковина з граніту", "long_description": "Раковина для ванної кімнати, полірування по замовленню.", "price": 3200, "images": ["/sample-images/sample4.jpg"]}, {"name": "Стол з граніту 'Грандіоз'", "short_description": "Монолітний стол з природнього каменю", "long_description": "Стіл для кухні або вулиці, вага залежить від розмірів.", "price": 12000, "images": ["/sample-images/sample5.jpg"]}, {"name": "Лавка з граніту 'Скам'", "short_description": "Надійна лавка для парку або двору", "long_description": "Лавка з міцного граніту, стійка до погодних умов.", "price": 5600, "images": ["/sample-images/sample6.jpg"]}, {"name": "Підвіконня гранітне 'Екстра'", "short_description": "Підвіконня з натурального каменю", "long_description": "Підвіконня різних розмірів, стійке до подряпин.", "price": 980, "images": ["/sample-images/sample7.jpg"]}, {"name": "Балясина 'Вертикаль'", "short_description": "Декоративні балясини з граніту", "long_description": "Окремі елементи для сходів та огорож, різні стилі.", "price": 750, "images": ["/sample-images/sample8.jpg"]}, {"name": "Плита облицювальна 'Класік'", "short_description": "Облицювальна плита для фасадів", "long_description": "Висока зносостійкість та естетика.", "price": 650, "images": ["/sample-images/sample9.jpg"]}, {"name": "Ваза декоративна 'Флора'", "short_description": "Декоративна ваза з граніту", "long_description": "Оригінальний декор для садів та інтер'єру.", "price": 2200, "images": ["/sample-images/sample10.jpg"]}]
  await col.deleteMany({})
  const r = await col.insertMany(sample)
  res.status(200).json({ inserted: r.insertedCount })
}
